### ISSUE TITLE
Can’t compile out of the box

### ISSUE THREAD

**Issue by alex-taffe** [lbrndnr/nuage-macos#3]
The `SoundCloud` library and `StackNavigationView` seem to not be committed to git. They should probably use the swift package manager instead. I can submit a PR for this, but wasnt sure if there was a reason why this was done this way

**Comment by lbrndnr** [comment]
Yeah you're right of course. The problem is that as far as I know, the swift package manager does not allow local repositories, at least not in a particularly useful way. This made it a bit difficult to work on these two frameworks.
I wasn't expecting anybody to contribute to Nuage this quickly so I guess I will add them again via the swift package manager :)

**Comment by alex-taffe** [comment]
@lbrndnr You actually can. If you just drag the package folder into Xcode on the sidebar, it’ll add it as a local repo and it functions the same way as a remote one. Or just setup git submodules

**Comment by lbrndnr** [comment]
Gimme one sec, I have it fixed in a moment

**Comment by lbrndnr** [comment]
This should be working now. Let me know if you have any other issues :)

**Comment by swiatrzyk** [comment]
Can't compile for the same reason (missing SoundCloud framework)

**Comment by lbrndnr** [comment]
@swiatrzyk you can use `https://github.com/lbrndnr/nuage-macos` to checkout SoundCloud framework as well. It's a git submodule :)

**Comment by swiatrzyk** [comment]
Thanks, problem solved 👍🏼
