### ISSUE TITLE
Crash on login and subsequent launches

### ISSUE THREAD

**Issue by lukaskubanek** [lbrndnr/nuage-macos#9]
As mentioned in [this tweet](https://twitter.com/lukaskubanek/status/1366444330332921857) I encountered a crash when I tried to log in into SoundCloud and now the app keeps crashing every time I launch it. You can find the crash report in [this gist](https://gist.github.com/lukaskubanek/790112217cc42e7831819d975219b9f3). My SoundCloud username is `lukaskubanek`. I’d be happy to help you further with resolving the issue.

**Comment by lbrndnr** [comment]
Hi @lukaskubanek, thanks for opening the issue :) The problem is that I don't have access to the API's documentation since it's all private. That's why it's kinda difficult for me to know what exactly is going on. I'm assuming that you liked a station or any other model I haven't implemented yet, which of course crashes when parsed. 
It would be easiest if you quickly checked out the repo and ran it yourself. That way we could figure out what exactly is causing the issue. Then I could quickly implement the new model, whichever is missing :)

**Comment by lukaskubanek** [comment]
@lbrndnr Indeed, it looks like it’s expecting a like of a playlist and it’s getting something else. Is there a simple way to view the incoming JSON I could look into? The stack trace isn’t of much help due to the Combine pipeline.

**Comment by lbrndnr** [comment]
Sorry for the late response, uni started again :)
You could add something like 
```
            .map { data in
                print(String(data: data, encoding: .utf8))
                return data
            }
```
in the `get` function in `SoundCloud.swift` line 100, right before `decode(type: T.self, decoder: decoder)` is called :)

**Comment by lukaskubanek** [comment]
It looks like it has something to do with [my two playlists](https://soundcloud.com/lukaskubanek/sets). I’ve mailed you the JSON response as I don’t want to post it here publicly. Let me know if I can help further.

**Comment by lbrndnr** [comment]
Fixed this issue in the latest commit. System playlists can still not be viewed correctly, but at least the app doesn't crash anymore :)
